export const Registration = 'Registration'
export const Users = 'User'
export const Customers = 'Customer'
export const Reports = 'Report'
export const Integrations = 'Integration'
export const LastQuater = 'LastQuater'
export const YearSale = 'YearSale'
export const CurrentMonth = 'SuperAdmin'
export const STORE_ACTION = 'STORE_ACTION'
export const STORE_STYLE = 'STORE_STYLE'
export const LOGIN_STYLE = 'LOGIN_STYLE'
export const STORE_TAB = 'STORE_TAB'
export const FETCH_USER_REQUEST = 'FETCH_USER_REQUEST'
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS'
export const FETCH_USER_FAILURE = 'FETCH_USER_FAILURE'
export const POST_IMAGE_REQUEST = 'POST_IMAGE_REQUEST'
export const POST_IMAGE_SUCCESS = 'POST_IMAGE_SUCCESS'
export const POST_IMAGE_FAILURE = 'POST_IMAGE_FAILURE'
export const POST_USER_REQUEST = 'POST_USER_REQUEST'
export const POST_USER_SUCCESS = 'POST_USER_SUCCESS'
export const POST_USER_FAILURE = 'POST_USER_FAILURE'
export const FETCH_ROLE_REQUEST = 'FETCH_ROLE_REQUEST'
export const FETCH_ROLE_SUCCESS = 'FETCH_ROLE_SUCCESS'
export const FETCH_ROLE_FAILURE = 'FETCH_ROLE_FAILURE'
export const FETCH_COUNTRY_REQUEST = 'FETCH_COUNTRY_REQUEST'
export const FETCH_COUNTRY_SUCCESS = 'FETCH_COUNTRY_SUCCESS'
export const FETCH_COUNTRY_FAILURE = 'FETCH_COUNTRY_FAILURE'
export const FETCH_CREATION_REQUEST = 'FETCH_CREATION_REQUEST'
export const FETCH_CREATION_SUCCESS = 'FETCH_CREATION_SUCCESS'
export const FETCH_CREATION_FAILURE = 'FETCH_CREATION_FAILURE'

export const FETCH_DELETE_REQUEST = 'FETCH_DELETE_REQUEST'
export const FETCH_DELETE_SUCCESS = 'FETCH_DELETE_SUCCESS'
export const FETCH_DELETE_FAILURE = 'FETCH_DELETE_FAILURE'

export const TOGGLE_BUTTON = 'TOGGLE_BUTTON'

